import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoadingIndicator from "./ui/loading-indicator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dipak Paudel portfolio 2026",
  description: "Generated by create next app and love for the technology",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <h2>
            <Link href="/">logo</Link>
          </h2>
          <h2>
            <Link href="/blogs" prefetch={false}>
              blogs
              <LoadingIndicator />
            </Link>
          </h2>
          <h2>
            <Link href="/projects">projects</Link>
          </h2>
          <h2>
            <Link href="/contact">contact</Link>
          </h2>
          <h2>
            <Link href="/login">Login</Link>
          </h2>
        </div>
        {children}
      </body>
    </html>
  );
}
