import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoadingIndicator from "./ui/loading-indicator";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dipak Paudel portfolio 2026",
  description: "Generated by create next app and love for the technology",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="navbar">
          <h2>
            <Link href="/">Home</Link>
          </h2>
          <h2>
            <Link href="/blogs" prefetch={true}>
              <span>
                Blogs
                <LoadingIndicator />
              </span>
            </Link>
          </h2>
          <h2>
            <Link href="/projects">Projects</Link>
          </h2>
          <h2>
            <Link href="/contact">Contact</Link>
          </h2>
          <h2>
            {session ? (
              <Link href="/dashboard">Dashboard</Link>
            ) : (
              <Link href="/login">Login</Link>
            )}
          </h2>
        </div>
        {children}
        <>
          <div className="footer">
            <div className="footer-content">
              <Link href="/">Home</Link>
              <Link href="/blogs">Blogs</Link>
              <Link href="/contact">Contact</Link>
              <Link href="/projects">Projects</Link>
            </div>
            <div className="footer-bottom">
              <p>&copy; 2026 Dipak Paudel. All rights reserved.</p>
            </div>
          </div>
        </>
      </body>
    </html>
  );
}
